hostname = "nixosPC"
instance_name = "kongjianghost"
instance_id = "c8421026-7968-43e4-91d4-aea543eaaba5"
dhcp = true
listeners = [
    "tcp://0.0.0.0:11010",
    "udp://0.0.0.0:11010",
    "wg://0.0.0.0:11011",
]
rpc_portal = "0.0.0.0:0"

[network_identity]
network_name = "kongjianghost"
network_secret = "kongjian"

[[peer]]
uri = "tcp://39.104.77.44:11010"

[flags]
private_mode = true
